Repository abahmed/Deer, pull requests merged in 2018-10, with the labels that each got.

#159 Fix links in CONTRIBUTING.md
  AUTHORS.md
  docs/CONTRIBUTING.md
Labels: ready-for-review

#145 Fixed #134 Now you can delete a note even if not saved
  app/actions/note.js
  app/components/StatusModal.js
Labels: ready-for-review

#147 Fixes #135 Now you don't get an error when changing from saved and not saved notes
  app/actions/note.js
Labels: ready-for-review

#162 Adding section of useful links for developers
  docs/README.md
Labels: Documentation, ready-for-review

#166 Fix yesNoModal that was not translating buttons
  app/components/YesNoModal.js
  assets/locales/en/yesNoModal.json
Labels: enhancement, ready-for-review

#178 Fixes #177: Auto deployment using CI services
  .travis.yml
  README.md
  appveyor.yml
  deploy.js
  docs/List-of-dependencies.md
  electron-builder.yml
  package-lock.json
  package.json
  post-commit.sh
Labels: ready-for-review

#182 Combine screenshots in README into a gif
  README.md
  assets/images/screenshots.gif
Labels: ready-for-review
